==============================================
Neuralangelo Single GPU Training
Output: /blue/arthur.porto-biocosmos/jhennessy7.gatech/neural_single_20250717_001837
==============================================
Copying data...
Data ready: 138 images

Environment set for single GPU:
  CUDA_VISIBLE_DEVICES=0
  RANK=0
  WORLD_SIZE=1

Starting training with torchrun...
Training PID: 2528496
Traceback (most recent call last):
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    result = agent.run()
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 138, in wrapper
    result = f(*args, **kwargs)
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 711, in run
    result = self._invoke_run(role)
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 864, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 138, in wrapper
    result = f(*args, **kwargs)
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 683, in _initialize_workers
    self._rendezvous(worker_group)
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 138, in wrapper
    result = f(*args, **kwargs)
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 500, in _rendezvous
    rdzv_info = spec.rdzv_handler.next_rendezvous()
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 67, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
torch.distributed.DistNetworkError: The server socket has failed to listen on any local network address. port: 29500, useIpv6: false, code: -98, name: EADDRINUSE, message: address already in use
âœ— Training failed
Trying direct python command instead...
Traceback (most recent call last):
  File "/home/jhennessy7.gatech/augenblick/src/neuralangelo/train.py", line 104, in <module>
    main()
  File "/home/jhennessy7.gatech/augenblick/src/neuralangelo/train.py", line 58, in main
    init_dist(cfg.local_rank, rank=-1, world_size=-1)
  File "/home/jhennessy7.gatech/augenblick/src/neuralangelo/imaginaire/utils/distributed.py", line 27, in init_dist
    dist.init_process_group(backend=backend, init_method='env://', **kwargs)
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/c10d_logger.py", line 95, in wrapper
    func_return = func(*args, **kwargs)
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1710, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/rendezvous.py", line 278, in _env_rendezvous_handler
    store = _create_c10d_store(
  File "/home/jhennessy7.gatech/neuralangelo_b200_env/lib64/python3.9/site-packages/torch/distributed/rendezvous.py", line 198, in _create_c10d_store
    return TCPStore(
torch.distributed.DistNetworkError: The server socket has failed to listen on any local network address. port: 29500, useIpv6: false, code: -98, name: EADDRINUSE, message: address already in use
Both methods failed. Check logs:
/blue/arthur.porto-biocosmos/jhennessy7.gatech/neural_single_20250717_001837/training.log
/blue/arthur.porto-biocosmos/jhennessy7.gatech/neural_single_20250717_001837/training_direct.log

Commands saved to: /blue/arthur.porto-biocosmos/jhennessy7.gatech/neural_single_20250717_001837/commands.txt
Training output: /blue/arthur.porto-biocosmos/jhennessy7.gatech/neural_single_20250717_001837
